const clientes = [
    {
        cliente: 1,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 4,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 6,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 9,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 10,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 7,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 12,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 36,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 31,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 33,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 42,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 43,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 2,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 25,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 46,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 49,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 50,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 48,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 68,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 69,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 93,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 92,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 107,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 108,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 124,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 101,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 109,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 114,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 90,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3708,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 38,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3711,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3706,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3693,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3694,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3695,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3696,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3697,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3692,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3709,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3687,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3688,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3699,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3707,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3700,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3701,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3703,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3690,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3686,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 133,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3625,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3631,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3644,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3713,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3712,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3710,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3705,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3704,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3702,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3691,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3714,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3730,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 26,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3757,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3662,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3719,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3722,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3721,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3731,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3664,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3738,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3739,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3743,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3746,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3753,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3729,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3759,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 141,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3762,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3764,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3772,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3773,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3774,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3775,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3777,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3780,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3781,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3783,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3784,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3785,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3786,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3805,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3768,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3720,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3677,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3734,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        cliente: 3769,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3718,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3776,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3756,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3754,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3742,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3760,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3811,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3817,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3818,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3827,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3828,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3829,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3841,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3842,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3843,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3849,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3851,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3859,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3865,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3835,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3866,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3867,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3868,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3874,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3875,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3876,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3877,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3863,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3930,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3880,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3887,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3893,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3847,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3894,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3895,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3896,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3897,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3888,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3885,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3908,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3909,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3910,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3911,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3916,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3917,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3918,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3919,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3920,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3921,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3922,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3928,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3929,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3931,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3932,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3933,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3934,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3935,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3936,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    },
    {
        Cliente: 3937,
        nombre: "",
        categoria: "",
        fecha_inicio: "",
        familia: "",
        articulo: "",
        nombre_contrato: "",
        descripcion: "",
        cantidad: 0,
        moneda: "$",
        precio: 0,
        descuento: 0,
        total: 0,
        observaciones: "",
        razon_social: ""
    }
]

export default clientes